server:
  port: 80
  servlet:
    context-path:  /pageSql
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: pageSql
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: false
    suffix: .html
mybatis:
  mapper-locations: classpath*:/cn.abc.pagesql.dao/**/*.xml






